##########
# This is .travis.yml configuration file specifically for master and develop branch.
# The travis job should contains only unit and integration tests.
#
# To avoid this file from being overwritten by .travis.yml from other branches,
# please add the following to your local git config:
#   git config merge.ours.driver true
##########

branches:
  only:
    - master
    - develop
    - testing-infrastructure

language: scala

scala:
  - 2.10.5

jdk:
  - oraclejdk8

addons:
    postgresql: "9.3"
    apt:
      packages:
        - haveged

services:
  - docker

sudo: required

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

env:
  global:
    - PIO_HOME=`pwd`

  matrix:
    - BUILD_TYPE=Unit
    - BUILD_TYPE=Integration METADATA_REP=PGSQL EVENTDATA_REP=PGSQL MODELDATA_REP=PGSQL
    - BUILD_TYPE=Integration METADATA_REP=ELASTICSEARCH EVENTDATA_REP=HBASE MODELDATA_REP=LOCALFS
    - BUILD_TYPE=Integration METADATA_REP=ELASTICSEARCH EVENTDATA_REP=PGSQL MODELDATA_REP=HDFS

before_install:
  - unset SBT_OPTS JVM_OPTS
  - docker pull ziemin/pio-testing:spark_2.0.0
  - service haveged start

before_script:
  - ./tests/before_script.travis.sh

script:
  - ./tests/script.travis.sh

after_script:
  - ./tests/after_script.travis.sh
